from ai_dev_agent.models.types import AgentResult
from ai_dev_agent.services.requirement_reader import read_requirement_file
from ai_dev_agent.services.jira_client import get_jira_requirement
from ai_dev_agent.services.git_manager import (
    prepare_repo,
    ensure_git_repo,
    create_branch,
    commit_all,
    push,
)
from ai_dev_agent.services.framework_detector import detect_framework
from ai_dev_agent.services.repo_indexer import index_repo
from ai_dev_agent.services.context_builder import build_context
from ai_dev_agent.services.planner import create_plan
from ai_dev_agent.services.generator import generate_diff
from ai_dev_agent.services.diff_applier import apply_patch
from ai_dev_agent.services.validator import run_validation
from ai_dev_agent.services.github_client import create_github_pr

def run_agent(
    issue: str | None = None,
    requirement_file: str | None = None,
    repo: str | None = ".",
    repo_url: str | None = None,
    dry_run: bool = True,
    create_pr: bool = False,
    mock_ai: bool = False,
    mock_jira: bool = False,
    framework_override: str | None = None,
) -> AgentResult:
    requirement = (
        read_requirement_file(requirement_file)
        if requirement_file
        else get_jira_requirement(issue or "", mock=mock_jira)
    )

    repo_path = prepare_repo(repo, repo_url)
    ensure_git_repo(repo_path)

    branch_key = requirement.key or "requirement"
    branch = f"smartpr/{branch_key}".replace(" ", "-").lower()

    if not dry_run:
        create_branch(repo_path, branch)

    framework = detect_framework(repo_path, framework_override)
    chunks = index_repo(repo_path)
    context = build_context(requirement, chunks)
    plan = create_plan(requirement, context, framework, mock_ai=mock_ai)
    diff = generate_diff(requirement, plan, context, framework, mock_ai=mock_ai)

    changed = False
    if diff.strip():
        if dry_run:
            apply_patch(repo_path, diff, check_only=True)
        else:
            changed = apply_patch(repo_path, diff)

    validation = run_validation(repo_path)

    pr_url = None
    if create_pr and not dry_run:
        if not validation["ok"]:
            raise RuntimeError("Validation failed. PR not created.\n" + validation["logs"])
        committed = commit_all(repo_path, f"{requirement.key or 'REQ'}: {requirement.title}")
        if committed:
            push(repo_path, branch)
            pr_url = create_github_pr(
                branch,
                f"{requirement.key or 'REQ'}: {requirement.title}",
                f"Generated by SmartPR AI.\n\nSource: {requirement.source}",
            )

    return AgentResult(
        requirement_title=requirement.title,
        framework=framework,
        branch=None if dry_run else branch,
        changed=changed,
        validation_ok=validation["ok"],
        dry_run=dry_run,
        pr_url=pr_url,
        plan=plan.__dict__,
        logs=validation["logs"],
    )
